services:
  radar-processing:
    build: .
    volumes:
      - ~/data/rwlm:/data
    stdin_open: true
    tty: true

  auto:
    extends:
      service: radar-processing
    environment:
      - BAGS_PATH=/data/deployment_auto_nov2023
      - GT_PATH=/data/deployment_auto_nov2023/GT_Nov2023.csv

  # manual:
  #   extends:
  #     service: radar-processing
  #   environment:
  #     - BAG_PATH=/data/0_deg_1m.bag
